import Config

# Configure your database
config :avance, Avance.Repo,
  username: System.get_env("DBUSER") || "postgres",
  password: System.get_env("DBPASSWORD") || "postgres",
  hostname: System.get_env("DBHOST") || "localhost",
  database: "avance_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :avance, AvanceWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "0ce4mp2OEJrtZiaSXj1aHCdDlM8Dra5COtB5LqDzmzcbr70YO3NpZKpS4kXYS1/p",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:default, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:default, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix flowy.gen.cert
#
# Run `mix help flowy.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :avance, AvanceWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/avance_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :avance, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Include HEEx debug annotations as HTML comments in rendered markup
config :phoenix_live_view, :debug_heex_annotations, true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

config :flowy, :oidc,
  pem:
    "-----BEGIN PRIVATE KEY-----\nMIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCr96qoCcY3UQ3q\nGPW7tFMRPvfx0pwb2zyJ3qXIQdcbew0y2dzQRXcPoBoOYb6oo8XqnJEPYRY5itvm\nEkIqElkKJhbxMHARCKbz5klViEUIoGWdP4m0stdIDfb9ej+KEgki9jbWXM/DRnnd\nPzPKwWYQixo4R9ykKgE5qoFosEZcyn9itpXhukUYhdGxnV/f3iBH/osVApwmk49C\nEFIYKBem/Xks2BdETXdRSWA49BXCzUDlcu2lSiMCkpcSIUUv1bJx10uwqiLwJVIP\n5nFRgLp/m61Eczr4DEqeqkDR5Ix9O0pPc3ufnszlaVsAH075qG5WQYPMIsywG3mr\ncyXQ7L6VAgMBAAECggEAWijnWGKHgckFOo8LhvXr90bESAzbu98dxkrtMCkU1luV\nd+uxUaCZ459VCeVFSLVUtsSPaTjFpjWfROidt+EWvbNqo9l5Z/TZU1aRbD6dswAl\nRmRhllONe0GXFR5a4dDC6YmdBpZydzcj/VN9m/f5wwKrJIbIr2k2az1xy6lfupWx\nD2+wNNZ3QKrRc9hHADMdiiY/kPhAlslmnmsNWhWVCdmt5uDd2l8jLZulSispz/dN\nZJfV4KV0+m1EzVX1AlxaaNRJVba6DDIwW3ValDsfR6fs3wSY3Se1m3hTlD260ZZc\nyxiZPD0HaFXs1JgWolDA9iPmCoBtr5xLqTX+3Qy8AQKBgQD5jrRtTlASqubOOLGX\nGkqSydwkV6Vl409Y7Prjn25/0Zqgz67oCrvok1lZKEJ0Kbe0wBmviHg0lBODlNjb\nytKkVW9nmXjXIIsuPIggBVPeFfsmroMQFLdOBFQEKc3h+CqK0WuBSJkSfprC18nJ\nuIfQ6t5RMQpjGtNAeb4isYOFoQKBgQCwaC3Kmx0ZKZjrC2pNgbslkDnQIDBwBsDd\nKnRLFoj2bft+TD4R/qR4aiSTsBJ1WS4fwabE7wTpILI45sMAAxJ1Aj/SIoRTmOnb\nPsrP01CoLbsTUa4vwzN39bm5MgC9HxLn5KEg3ihzQPpsr/Tgyd0tnDoKJYH4Vbqy\n3WoW1DksdQKBgQC7Ydy2SlwzeCGv7L/kHniqOWnT2/+0Pnbg5agI7DhzPzZk0yyY\nzR6FJsaq/GDRilWHIcrnk4f2qszwOv6OIoABpqjs2D71AVmgURFBQd7UXhrj05tT\nosp0iSlwqtcNemKvM0oOnC1bxrZ74L2Ces14IDLoMfODsKu4uPD8ad/AoQKBgQCD\npBqX2Qzr3BjbPdeEI02PCIO8BmlfEAsYgDfsWNK4YvaMF0UylH4TxdGpzHjZzUUY\nOaDD0UIu3lFhGQNnnONHIfiSTWPGJpRNIhyi3iSQfB/gmNGNnvNnj52az++xMeEf\n34NGTcKNz22RcfUhUkKVaMH/FGJa+U6rb4Ndqd1IiQKBgQD0vg5zIHkyulJAa/84\nWI3bJ47K2B4aChjxSxSAlErkaxtxUNkKGAYET0KQppr9lB3YlMLaMOPNEspsx9Y/\nUe3hHntIf7FCe1eTzLXitahZQCTA2EDB3A+l7/C/BsZYlPLbA0tB0dUUBLTW8jOR\nmqyulmffKbN848GkbOF0z/ydqQ==\n-----END PRIVATE KEY-----\n",
  public_keys:
    "{\"keys\":[{\"kty\":\"RSA\",\"e\":\"AQAB\",\"use\":\"sig\",\"kid\":\"iTMxG6ONYMk-jsWFa8MwwG_BvTeNQRaRqTpcPBt8J3g\",\"alg\":\"RS256\",\"n\":\"q_eqqAnGN1EN6hj1u7RTET738dKcG9s8id6lyEHXG3sNMtnc0EV3D6AaDmG-qKPF6pyRD2EWOYrb5hJCKhJZCiYW8TBwEQim8-ZJVYhFCKBlnT-JtLLXSA32_Xo_ihIJIvY21lzPw0Z53T8zysFmEIsaOEfcpCoBOaqBaLBGXMp_YraV4bpFGIXRsZ1f394gR_6LFQKcJpOPQhBSGCgXpv15LNgXRE13UUlgOPQVws1A5XLtpUojApKXEiFFL9WycddLsKoi8CVSD-ZxUYC6f5utRHM6-AxKnqpA0eSMfTtKT3N7n57M5WlbAB9O-ahuVkGDzCLMsBt5q3Ml0Oy-lQ\"}]}",
  iss: "https://local.dev/",
  aud: "https://flowy.local.dev",
  jwks_uri: "http://localhost/jwks"
